global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'scalyr-blog'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name:       'go-chatserver'
    scrape_interval: 5s
    static_configs:
      - targets: ['chat_server:8080']
        labels:
          group: 'production'

  - job_name: redis_exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['redis_exporter:9121']
